# Additional scenario parameters

# USMCA and auto sector parameters
us_auto_content_share: 0.4      # Share of US content in auto assembly
us_auto_assembly_share: 0.33    # Share of US assembly in autos
auto_rebate_rate: 0.0375        # Auto rebate rate

# IEEPA parameters
ieepa_usmca_exception: 1        # Apply USMCA exemption to IEEPA tariffs (1 = yes, 0 = no)

# Country folding parameters for IEEPA rates
kr_share_ftrow: 0.57            # Korea's share to fold into ftrow
vn_share_row: 0.94              # Vietnam's share to fold into row
